version: 2.1
orbs:
  slack: circleci/slack@3.3.0
  gcp-cli: circleci/gcp-cli@2.4.1
  kubernetes: circleci/kubernetes@0.9.1
  helm: circleci/helm@2.0.1
  go: circleci/go@1.7.1
jobs:
  test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: go get -v ./...
      - run: go vet .
      - run: go install .

  integration:
    docker:
      - image: docker/tilt:latest

    steps:
      - checkout
      - helm/install-helm-client
      - run: |
          set -e
          mkdir -p /usr/local/go
          curl --fail --location -sS "https://dl.google.com/go/go1.18.3.linux-amd64.tar.gz" \
          | tar --no-same-owner --strip-components=1 --gunzip -x -C /usr/local/go/
          echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
          chown -R $(whoami) /usr/local/go
          /usr/local/go/bin/go version
      - setup_remote_docker:
          version: 20.10.11
      - run: ctlptl create cluster kind --registry=ctlptl-registry && tilt ci
      
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - kubernetes/install-kubectl
      - helm/install-helm-client
      - run:
          name: Setup Kubernetes
          command: gcloud container clusters get-credentials windmill
      - run:
          name: Setup Docker Credentials
          command: gcloud auth configure-docker
      - run: ./hack/deploy.sh
      - slack/status

workflows:
  version: 2
  test:
    jobs:
      - test
      - integration:
          requires:
            - test
  deploy:
    jobs:
      - deploy:
          context: Tilt Deploy Context
          filters:
            branches:
              only: main
